// Fallback menu items in case API fails
const fallbackMenuItems = [
  {
    key: "home",
    labelVi: "Trang chủ",
    labelEn: "Home",
    pathVi: "/",
    pathEn: "/en/",
  },
  {
    key: "products",
    labelVi: "Sản phẩm",
    labelEn: "Products",
    pathVi: "/san-pham",
    pathEn: "/en/products",
    submenu: [
      {
        key: "cns-atm",
        labelVi: "CNS/ATM",
        labelEn: "CNS/ATM",
        pathVi: "/san-pham/cns-atm",
        pathEn: "/en/products/cns-atm",
      },
      {
        key: "lighting-system",
        labelVi: "Hệ thống đèn hiệu",
        labelEn: "Lighting System",
        pathVi: "/san-pham/he-thong-den-hieu",
        pathEn: "/en/products/lighting-system",
      },
      {
        key: "shelter",
        labelVi: "Shelter",
        labelEn: "Shelter",
        pathVi: "/san-pham/shelter",
        pathEn: "/en/products/shelter",
      },
      {
        key: "console-desk",
        labelVi: "Bàn console",
        labelEn: "Console Desk",
        pathVi: "/san-pham/ban-console",
        pathEn: "/en/products/console-desk",
      },
      {
        key: "counterpoise",
        labelVi: "Giàn phản xạ VOR",
        labelEn: "Counterpoise",
        pathVi: "/san-pham/gian-phan-xa",
        pathEn: "/en/products/counterpoise",
      },
      {
        key: "audio-video-recording",
        labelVi: "Thiết bị ghi âm/ghi hình",
        labelEn: "Recording/ Video Equipment",
        pathVi: "/san-pham/ghi-am-ghi-hinh",
        pathEn: "/en/products/audio-video-recording",
      },
      {
        key: "other-equipment",
        labelVi: "Các sản phẩm dân dụng khác",
        labelEn: "Other Equipment",
        pathVi: "/san-pham/thiet-bi-dan-dung",
        pathEn: "/en/products/other-equipment",
      },
      {
        key: "vr360",
        labelVi: "VR 360",
        labelEn: "VR 360",
        pathVi: "https://attech.vr360.one/",
        pathEn: "https://attech.vr360.one/en",
      },
    ],
  },
  {
    key: "services",
    labelVi: "Dịch vụ",
    labelEn: "Services",
    pathVi: "/dich-vu",
    pathEn: "/en/services",
    submenu: [
      {
        key: "cns-service",
        labelVi: "Dịch vụ thông tin dẫn đường giám sát (CNS)",
        labelEn: "CNS Service",
        pathVi: "/dich-vu/thong-tin-dan-duong-giam-sat",
        pathEn: "/en/services/cns-service",
      },
      {
        key: "calibration-service",
        labelVi: "Dịch vụ Bay kiểm tra hiệu chuẩn",
        labelEn: "Calibration Service",
        pathVi: "/dich-vu/bay-kiem-tra-hieu-chuan",
        pathEn: "/en/services/calibration-service",
      },
      {
        key: "testing-calibration-service",
        labelVi: "Dịch vụ Thử nghiệm - Hiệu chuẩn",
        labelEn: "Testing - Calibration Service",
        pathVi: "/dich-vu/thu-nghiem-hieu-chuan",
        pathEn: "/en/services/testing-calibration-service",
      },
      {
        key: "aviation-service",
        labelVi: "Dịch vụ Kỹ thuật (Hàng không)",
        labelEn: "Aviation Service",
        pathVi: "/dich-vu/ky-thuat-hang-khong",
        pathEn: "/en/services/aviation-service",
      },
      {
        key: "training-education-service",
        labelVi: "Dịch vụ Huấn luyện - Đào tạo",
        labelEn: "Training - Education Service",
        pathVi: "/dich-vu/huan-luyen-dao-tao",
        pathEn: "/en/services/training-education-service",
      },
      {
        key: "consulting-qlda-service",
        labelVi: "Dịch vụ Tư vấn đầu tư và xây dựng QLDA",
        labelEn: "Consulting - QLDA Service",
        pathVi: "/dich-vu/tu-van-dau-tu-xay-dung-qlda",
        pathEn: "/en/services/consulting-qlda-service",
      },
    ],
  },
  {
    key: "news",
    labelVi: "Tin tức",
    labelEn: "News",
    pathVi: "/tin-tuc",
    pathEn: "/en/news",
    submenu: [
      {
        key: "activities",
        labelVi: "Tin hoạt động",
        labelEn: "Activities",
        pathVi: "/tin-tuc/tin-hoat-dong",
        pathEn: "/en/news/activities",
        submenu: [
          {
            key: "company-activities",
            labelVi: "Hoạt động Công ty",
            labelEn: "Company Activities",
            pathVi: "/tin-tuc/hoat-dong-cong-ty",
            pathEn: "/en/news/company-activities",
          },
          {
            key: "company-party",
            labelVi: "Đảng bộ Công ty",
            labelEn: "Company Party",
            pathVi: "/tin-tuc/dang-bo-cong-ty",
            pathEn: "/en/news/company-party",
          },
          {
            key: "company-youth-union",
            labelVi: "Đoàn thanh niên Công ty",
            labelEn: "Company Youth Union",
            pathVi: "/tin-tuc/doan-thanh-nien-cong-ty",
            pathEn: "/en/news/company-youth-union",
          },
          {
            key: "company-union",
            labelVi: "Công đoàn Công ty",
            labelEn: "Company Union",
            pathVi: "/tin-tuc/cong-doan-cong-ty",
            pathEn: "/en/news/company-union",
          },
        ],
      },
      {
        key: "aviation-news",
        labelVi: "Tin ngành hàng không",
        labelEn: "Aviation News",
        pathVi: "/tin-tuc/tin-nganh-hang-khong",
        pathEn: "/en/news/aviation-news",
      },
      {
        key: "legal-propaganda",
        labelVi: "Tuyên truyền pháp luật",
        labelEn: "Legal Propaganda",
        pathVi: "/tin-tuc/tuyen-truyen-phap-luat",
        pathEn: "/en/news/legal-propaganda",
      },
    ],
  },
  {
    key: "notifications",
    labelVi: "Thông báo",
    labelEn: "Notifications",
    pathVi: "/thong-bao",
    pathEn: "/en/notifications",
    submenu: [
      {
        key: "recruitment",
        labelVi: "Tuyển dụng",
        labelEn: "Recruitment",
        pathVi: "/thong-bao/tuyen-dung",
        pathEn: "/en/notifications/recruitment",
      },
      {
        key: "supplier-notice",
        labelVi: "Thông báo mời nhà cung cấp",
        labelEn: "Supplier Notice",
        pathVi: "/thong-bao/moi-nha-cung-cap",
        pathEn: "/en/notifications/supplier-notice",
      },
      {
        key: "other-notices",
        labelVi: "Thông báo khác",
        labelEn: "Other Notices",
        pathVi: "/thong-bao/thong-bao-khac",
        pathEn: "/en/notifications/other-notices",
      },
    ],
  },
  {
    key: "company",
    labelVi: "Thông tin Công ty",
    labelEn: "Company Info",
    pathVi: "/thong-tin-cong-ty",
    pathEn: "/en/company",
    submenu: [
      {
        key: "history",
        labelVi: "Lịch sử ra đời",
        labelEn: "History",
        pathVi: "/thong-tin-cong-ty/lich-su-ra-doi",
        pathEn: "/en/company/history",
      },
      {
        key: "structure",
        labelVi: "Cơ cấu tổ chức",
        labelEn: "Structure",
        pathVi: "/thong-tin-cong-ty/co-cau-to-chuc",
        pathEn: "/en/company/structure",
      },
      {
        key: "leadership",
        labelVi: "Ban lãnh đạo",
        labelEn: "Leadership",
        pathVi: "/thong-tin-cong-ty/ban-lanh-dao",
        pathEn: "/en/company/leadership",
      },
      {
        key: "business",
        labelVi: "Ngành nghề kinh doanh",
        labelEn: "Business",
        pathVi: "/thong-tin-cong-ty/nganh-nghe-kinh-doanh",
        pathEn: "/en/company/business",
      },
      {
        key: "iso",
        labelVi: "Hệ thống chứng chỉ ISO",
        labelEn: "ISO Certificates",
        pathVi: "/thong-tin-cong-ty/he-thong-chung-chi-iso",
        pathEn: "/en/company/iso",
      },
      {
        key: "financial-info",
        labelVi: "Thông tin tài chính",
        labelEn: "Financial Info",
        pathVi: "/thong-tin-cong-ty/thong-tin-tai-chinh",
        pathEn: "/en/company/finance",
      },
      {
        key: "gallery",
        labelVi: "Thư viện Công ty",
        labelEn: "Company Gallery",
        pathVi: "/thong-tin-cong-ty/thu-vien-cong-ty",
        pathEn: "/en/company/gallery",
      },
    ],
  },
  {
    key: "contact",
    labelVi: "Liên hệ",
    labelEn: "Contact",
    pathVi: "/lien-he",
    pathEn: "/en/contact",
  },
];

export default fallbackMenuItems;
